version: "3.7"

services:
  
  
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cliente
      MYSQL_ROOT_PASSWORD: a_password
      
  clientes-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: cliente
      DATABASE_USER: root
      DATABASE_PASSWORD: a_password